services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=mcl_site.settings.dev
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    stdin_open: true
    tty: true
