# Generated by Django 5.0.14 on 2025-12-21 21:51

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Вступний текст')),
            ],
            options={
                'verbose_name': 'Сторінка новин',
                'verbose_name_plural': 'Сторінки новин',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='newspage',
            options={'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
    ]
