# Generated by Django 5.1.15 on 2026-05-12 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newspagetag_newspage_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsindexpage',
            options={'verbose_name': 'Новини (системна)', 'verbose_name_plural': 'Новини'},
        ),
    ]
