# Generated by Django 5.2.17 on 2026-08-30 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_newspage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsindexpage',
            options={'verbose_name': 'Новини', 'verbose_name_plural': 'Новини'},
        ),
    ]
