# Generated by Django 5.2.17 on 2026-08-30 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_newsindexpage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspage',
            options={'ordering': ['-date', '-first_published_at'], 'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
    ]
