# Generated by Django 5.1.15 on 2025-12-24 22:26

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва розділу')),
                ('icon', models.CharField(default='bi-folder', help_text='Наприклад: bi-book, bi-file-text, bi-calendar', max_length=50, verbose_name='Іконка (Bootstrap Icons)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_expanded', models.BooleanField(default=False, verbose_name='Розгорнуто за замовчуванням')),
            ],
            options={
                'verbose_name': 'Розділ бічної панелі',
                'verbose_name_plural': 'Розділи бічної панелі',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='page',
        ),
        migrations.CreateModel(
            name='SidebarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=100, verbose_name='Текст посилання')),
                ('external_url', models.URLField(blank=True, verbose_name='Зовнішнє посилання')),
                ('new_tab', models.BooleanField(default=False, verbose_name='Відкрити у новій вкладці')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Сторінка')),
                ('section', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.sidebarsection')),
            ],
            options={
                'verbose_name': 'Посилання',
                'verbose_name_plural': 'Посилання',
            },
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
