# Generated by Django 5.1.15 on 2025-12-28 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryindexpage',
            options={'verbose_name': 'Галерея (системна)'},
        ),
    ]
