# Generated by Django 5.1.15 on 2025-12-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_galleryindexpage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryalbumpage',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата події'),
        ),
    ]
