# Generated by Django 5.1.15 on 2026-05-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_galleryalbumpage_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryalbumpage',
            options={'ordering': ['-first_published_at'], 'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбоми'},
        ),
    ]
