# Generated by Django 5.2.17 on 2026-08-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_galleryalbumpage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryalbumpage',
            options={'ordering': ['-date', '-first_published_at'], 'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбоми'},
        ),
    ]
