# Generated by Django 5.0.14 on 2025-12-22 14:30

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpage',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кваліфікаційна категорія'),
        ),
        migrations.AddField(
            model_name='personpage',
            name='education',
            field=models.CharField(blank=True, max_length=255, verbose_name='Освіта'),
        ),
        migrations.AddField(
            model_name='personpage',
            name='experience',
            field=models.CharField(blank=True, max_length=50, verbose_name='Стаж роботи'),
        ),
        migrations.AlterField(
            model_name='personpage',
            name='bio',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Біографія та досягнення'),
        ),
    ]
