# Generated by Django 5.0.14 on 2025-12-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_personpage_category_personpage_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpage',
            name='is_administration',
            field=models.BooleanField(default=False, verbose_name='Керівництво (адміністрація)'),
        ),
    ]
