# Generated by Django 5.1.15 on 2025-12-22 20:12

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_personpage_is_administration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personpage',
            name='subject',
            field=models.CharField(blank=True, max_length=100, verbose_name='Предмет (застаріле)'),
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Назва предмета')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='staff.personpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
