# Generated by Django 5.1.15 on 2025-12-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_personpage_subject_teachersubject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personpage',
            name='subject',
        ),
    ]
