# Generated by Django 5.1.15 on 2025-12-22 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_remove_personpage_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personpage',
            name='is_administration',
        ),
    ]
