# Generated by Django 5.1.15 on 2025-12-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_remove_personpage_is_administration'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpage',
            name='department',
            field=models.CharField(blank=True, help_text='Наприклад: Кафедра філології, Кафедра точних наук', max_length=200, verbose_name='Кафедра'),
        ),
    ]
