# Generated by Django 5.1.15 on 2026-05-12 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_personpage_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffindexpage',
            options={'verbose_name': 'Колектив (системна)', 'verbose_name_plural': 'Колектив (системна)'},
        ),
    ]
