# Generated by Django 5.1.15 on 2026-05-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_alter_staffindexpage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personpage',
            options={'ordering': ['-first_published_at'], 'verbose_name': 'Співробітник', 'verbose_name_plural': 'Співробітники'},
        ),
        migrations.AlterModelOptions(
            name='teachersubject',
            options={'verbose_name': 'Предмет викладача', 'verbose_name_plural': 'Предмети викладача'},
        ),
    ]
