# Generated by Django 5.2.17 on 2026-08-30 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_alter_personpage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffindexpage',
            options={'verbose_name': 'Колектив', 'verbose_name_plural': 'Колектив'},
        ),
    ]
