# Generated by Django 5.1.15 on 2025-12-23 20:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationformpage',
            name='rules_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Текст з правилами вступу, необхідними документами, датами тощо', verbose_name='Правила вступу'),
        ),
    ]
