# Generated by Django 5.1.15 on 2026-05-12 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_applicationformpage_rules_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationformpage',
            options={'verbose_name': 'Вступ (системна)', 'verbose_name_plural': 'Вступ (системна)'},
        ),
    ]
