# Generated by Django 5.1.15 on 2026-08-02 20:17

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_alter_applicationformpage_options'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationformpage',
            options={'verbose_name': 'Вступ', 'verbose_name_plural': 'Вступ'},
        ),
        migrations.AddField(
            model_name='applicationformpage',
            name='sample_application_description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Короткі вказівки, як заповнити та підписати заяву перед фотографуванням', verbose_name='Інструкція до заяви / опис зразка'),
        ),
        migrations.AddField(
            model_name='applicationformpage',
            name='sample_application_document',
            field=models.ForeignKey(blank=True, help_text='Документ-бланк зразка заяви для завантаження', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Зразок заяви (скачуваний документ PDF/DOCX)'),
        ),
        migrations.AddField(
            model_name='applicationformpage',
            name='sample_application_image',
            field=models.ForeignKey(blank=True, help_text='Зображення зразка заяви для перегляду у формі', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Зразок заяви (зображення)'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field'), ('file', 'Файл / Фото заяви'), ('image', 'Зображення')], max_length=16, verbose_name='Тип поля'),
        ),
    ]
