# Generated by Django 5.1.15 on 2026-08-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_alter_applicationformpage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationformpage',
            name='google_form_url',
            field=models.URLField(blank=True, help_text='Вставте посилання для вбудовування з Google Forms. Відкрийте форму → Надіслати → < > → скопіюйте src з iframe. Приклад: https://docs.google.com/forms/d/e/…/viewform?embedded=true', max_length=500, verbose_name='Посилання Google Form (embed)'),
        ),
    ]
