# Generated by Django 5.1.15 on 2026-08-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_add_google_form_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationformpage',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='applicationformpage',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='applicationformpage',
            name='thank_you_text',
        ),
        migrations.RemoveField(
            model_name='applicationformpage',
            name='to_address',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
    ]
