# Generated by Django 5.1.15 on 2026-08-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_cleanup_unused_form_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationformpage',
            name='sample_application_description',
        ),
        migrations.RemoveField(
            model_name='applicationformpage',
            name='sample_application_document',
        ),
        migrations.RemoveField(
            model_name='applicationformpage',
            name='sample_application_image',
        ),
    ]
