# Generated by Django 5.0.14 on 2025-12-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classgroup',
            options={'ordering': ['name'], 'verbose_name': 'Клас', 'verbose_name_plural': 'Класи'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['week', 'day', 'lesson_number', 'class_group'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предмети'},
        ),
        migrations.AddField(
            model_name='classgroup',
            name='study_type',
            field=models.CharField(choices=[('ОЧНЕ', 'Очне'), ('ДИСТ.', 'Дистанційне')], default='ОЧНЕ', max_length=20, verbose_name='Тип навчання'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='cabinet',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Кабінет'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='week',
            field=models.IntegerField(choices=[(1, 'I тиждень'), (2, 'II тиждень'), (0, 'Обидва тижні')], default=0, verbose_name='Тиждень'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Клас'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_number',
            field=models.PositiveIntegerField(verbose_name='Номер уроку (пари)'),
        ),
    ]
