# Generated by Django 5.0.14 on 2025-12-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_classgroup_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='week',
            field=models.IntegerField(choices=[(1, 'I тиждень'), (2, 'II тиждень'), (3, 'III тиждень'), (4, 'IV тиждень')], default=0, verbose_name='Тиждень'),
        ),
    ]
