# Generated by Django 5.0.14 on 2025-12-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_lesson_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='sub_group',
            field=models.IntegerField(choices=[(0, 'Весь клас'), (1, '1 підгрупа'), (2, '2 підгрупа')], default=0, verbose_name='Підгрупа'),
        ),
    ]
