# Generated by Django 5.0.14 on 2025-12-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_lesson_sub_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['week', 'day', 'para_number', 'para_part', 'class_group'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_number',
        ),
        migrations.AddField(
            model_name='lesson',
            name='para_number',
            field=models.IntegerField(choices=[(1, 'I пара'), (2, 'II пара'), (3, 'III пара'), (4, 'IV пара')], default=1, verbose_name='Номер пари'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='para_part',
            field=models.IntegerField(choices=[(0, 'Повна пара'), (1, '1-ша половина'), (2, '2-га половина')], default=0, verbose_name='Частина пари'),
        ),
    ]
