# Generated by Django 5.0.14 on 2025-12-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_lesson_options_remove_lesson_lesson_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='week',
            field=models.IntegerField(choices=[(1, 'I тиждень'), (2, 'II тиждень'), (3, 'III тиждень'), (4, 'IV тиждень')], default=1, verbose_name='Тиждень (I-IV)'),
        ),
    ]
