# Generated by Django 6.0.7 on 2026-08-27 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_lesson_week'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year_structure_title', models.CharField(blank=True, default='Структура навчального року', help_text="Необов'язково. За замовчуванням: 'Структура навчального року'", max_length=255, verbose_name='Назва (Структура навчального року)')),
                ('semester_weeks_title', models.CharField(blank=True, default='Тижні семестру навчального року', help_text="Необов'язково. За замовчуванням: 'Тижні семестру навчального року'", max_length=255, verbose_name='Назва (Тижні семестру)')),
                ('academic_year_structure_doc', models.ForeignKey(blank=True, help_text='Документ зі структурою навчального року (PDF/DOCX тощо)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Структура навчального року')),
                ('semester_weeks_doc', models.ForeignKey(blank=True, help_text='Документ з тижнями семестру навчального року (PDF/DOCX тощо)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Тижні семестру навчального року')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Налаштування розкладу та документи',
                'verbose_name_plural': 'Налаштування розкладу та документи',
            },
        ),
    ]
