# Generated by Django 5.1.15 on 2025-12-24 21:03

import django.db.models.deletion
import django.utils.timezone
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Вступний текст')),
            ],
            options={
                'verbose_name': 'Сторінка публічних документів',
                'verbose_name_plural': 'Сторінки публічних документів',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PublicDocumentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Опис')),
                ('doc_type', models.CharField(choices=[('policy', 'Політика та нормативні акти'), ('schedule', 'Розклад та дзвінки'), ('safety', 'Безпека і рекомендації'), ('admissions', 'Вступ'), ('other', 'Інше')], default='other', max_length=32, verbose_name='Тип документу')),
                ('year', models.PositiveSmallIntegerField(default=2025, verbose_name='Рік')),
                ('doc_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Файл документа')),
            ],
            options={
                'verbose_name': 'Публічний документ',
                'verbose_name_plural': 'Публічні документи',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PublicDocumentPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='documents.publicdocumentpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='publicdocumentpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='documents.PublicDocumentPageTag', to='taggit.Tag', verbose_name='Теги'),
        ),
    ]
