# Generated by Django 5.1.15 on 2025-12-24 22:16

import django.db.models.deletion
from django.db import migrations, models


def create_default_types_and_migrate(apps, schema_editor):
    """Create default document types and migrate existing data"""
    DocumentType = apps.get_model('documents', 'DocumentType')
    PublicDocumentPage = apps.get_model('documents', 'PublicDocumentPage')
    
    # Create default types based on old choices
    default_types = [
        ("policy", "Політика та нормативні акти"),
        ("schedule", "Розклад та дзвінки"),
        ("safety", "Безпека і рекомендації"),
        ("admissions", "Вступ"),
        ("other", "Інше"),
    ]
    
    type_mapping = {}
    for slug, name in default_types:
        doc_type, _ = DocumentType.objects.get_or_create(slug=slug, defaults={'name': name})
        type_mapping[slug] = doc_type
    
    # Migrate existing documents
    for page in PublicDocumentPage.objects.all():
        old_type = page.doc_type_old
        if old_type and old_type in type_mapping:
            page.doc_type = type_mapping[old_type]
            page.save()


def reverse_migrate(apps, schema_editor):
    """Reverse migration - copy FK back to string"""
    PublicDocumentPage = apps.get_model('documents', 'PublicDocumentPage')
    for page in PublicDocumentPage.objects.all():
        if page.doc_type:
            page.doc_type_old = page.doc_type.slug
            page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        # Step 1: Create DocumentType model
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(help_text='Унікальний ідентифікатор (латиницею, без пробілів)', max_length=100, unique=True, verbose_name='Ідентифікатор')),
            ],
            options={
                'verbose_name': 'Тип документу',
                'verbose_name_plural': 'Типи документів',
                'ordering': ['name'],
            },
        ),
        # Step 2: Rename old doc_type field to doc_type_old
        migrations.RenameField(
            model_name='publicdocumentpage',
            old_name='doc_type',
            new_name='doc_type_old',
        ),
        # Step 3: Add new doc_type FK field
        migrations.AddField(
            model_name='publicdocumentpage',
            name='doc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documenttype', verbose_name='Тип документу'),
        ),
        # Step 4: Migrate data
        migrations.RunPython(create_default_types_and_migrate, reverse_migrate),
        # Step 5: Remove old field
        migrations.RemoveField(
            model_name='publicdocumentpage',
            name='doc_type_old',
        ),
    ]
