# Generated by Django 5.1.15 on 2026-05-12 21:32

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_add_document_type_snippet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentsindexpage',
            options={'verbose_name': 'Документи (системна)', 'verbose_name_plural': 'Документи'},
        ),
        migrations.AlterField(
            model_name='publicdocumentpage',
            name='year',
            field=models.PositiveSmallIntegerField(default=documents.models.current_year, verbose_name='Рік'),
        ),
    ]
