# Generated by Django 5.1.15 on 2026-05-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documentsindexpage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicdocumentpage',
            options={'ordering': ['-first_published_at'], 'verbose_name': 'Публічний документ', 'verbose_name_plural': 'Публічні документи'},
        ),
    ]
