# Generated by Django 5.2.17 on 2026-08-30 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_publicdocumentpage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentsindexpage',
            options={'verbose_name': 'Документи', 'verbose_name_plural': 'Документи'},
        ),
    ]
