# Generated by Django 5.1.15 on 2025-12-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body_heroimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
