# Generated by Django 5.1.15 on 2025-12-22 23:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='subtitle',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Підзаголовок'),
        ),
    ]
