# Generated by Django 5.1.15 on 2025-12-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_aboutpage_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, verbose_name='Підзаголовок'),
        ),
    ]
