# Generated by Django 5.1.15 on 2025-12-24 21:55

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_documentpage_educationpage_standardpage_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': '[Застаріла] Сторінка Про нас'},
        ),
        migrations.AlterModelOptions(
            name='documentpage',
            options={'verbose_name': '[Застаріла] Сторінка документів'},
        ),
        migrations.AlterModelOptions(
            name='educationpage',
            options={'verbose_name': '[Застаріла] Сторінка навчання'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Головна сторінка'},
        ),
        migrations.AlterModelOptions(
            name='standardpage',
            options={'verbose_name': '[Застаріла] Стандартна сторінка'},
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='icon',
            field=models.CharField(blank=True, help_text='Наприклад: bi-calendar-event, bi-file-earmark-person', max_length=100, verbose_name='Іконка (Bootstrap Icons)'),
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Підзаголовок')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Вміст')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Сторінка контенту',
                'verbose_name_plural': 'Сторінки контенту',
            },
            bases=('wagtailcore.page',),
        ),
    ]
