# Generated by Django 5.1.15 on 2025-12-24 22:40

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_aboutpage_options_alter_documentpage_options_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'Сторінка Про нас'},
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='body',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='achievements',
            field=wagtail.fields.RichTextField(blank=True, help_text='Ключові досягнення закладу', verbose_name='Досягнення'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='building_image',
            field=models.ForeignKey(blank=True, help_text='Фото будівлі або території закладу', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фото закладу'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Рік заснування'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='history',
            field=wagtail.fields.RichTextField(blank=True, help_text='Історія закладу', verbose_name='Історія'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Коротке представлення закладу', verbose_name='Вступний текст'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='logo',
            field=models.ForeignKey(blank=True, help_text="Логотип для секції 'Про нас'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Логотип закладу'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission',
            field=wagtail.fields.RichTextField(blank=True, help_text='Місія та цілі закладу', verbose_name='Місія'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='students_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кількість учнів'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='teachers_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кількість вчителів'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='values',
            field=wagtail.fields.RichTextField(blank=True, help_text='Основні цінності та принципи', verbose_name='Цінності'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Короткий слоган або девіз закладу', max_length=500, verbose_name='Девіз/Слоган'),
        ),
    ]
