# Generated by Django 5.1.15 on 2025-12-28 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_aboutpage_options_remove_aboutpage_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'Про нас (системна)'},
        ),
    ]
