# Generated by Django 5.1.15 on 2026-05-18 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_aboutpage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='logo',
        ),
    ]
