# Generated by Django 5.1.15 on 2026-07-21 19:51

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_aboutpage_logo'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Підзаголовок')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Вступний текст')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Сторінка розділу',
                'verbose_name_plural': 'Сторінки розділів',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Вміст')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адреса')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Контакти',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EducationalProcessIndexPage',
            fields=[
                ('sectionindexpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.sectionindexpage')),
            ],
            options={
                'verbose_name': 'Освітній процес',
            },
            bases=('home.sectionindexpage',),
        ),
        migrations.CreateModel(
            name='EducationalWorkIndexPage',
            fields=[
                ('sectionindexpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.sectionindexpage')),
            ],
            options={
                'verbose_name': 'Виховна робота',
            },
            bases=('home.sectionindexpage',),
        ),
        migrations.CreateModel(
            name='PublicInformationIndexPage',
            fields=[
                ('sectionindexpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.sectionindexpage')),
            ],
            options={
                'verbose_name': 'Публічна інформація',
            },
            bases=('home.sectionindexpage',),
        ),
        migrations.CreateModel(
            name='ParentsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Підзаголовок')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Вміст')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Батькам',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TeachersPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Підзаголовок')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Вміст')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Педагогам',
            },
            bases=('wagtailcore.page',),
        ),
    ]
