# Generated by Django 5.1.15 on 2026-08-02 12:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_sectionindexpage_contactspage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='announcement',
            field=wagtail.fields.RichTextField(blank=True, help_text='Текст оголошення, що відображається на головній сторінці під шапкою. Залиште порожнім, щоб приховати.', verbose_name='Оголошення'),
        ),
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'Про нас'},
        ),
        # Delete child models first (they have FK/ptr to parent models)
        migrations.DeleteModel(name='ContactsPage'),
        migrations.DeleteModel(name='EducationalProcessIndexPage'),
        migrations.DeleteModel(name='EducationalWorkIndexPage'),
        migrations.DeleteModel(name='PublicInformationIndexPage'),
        migrations.DeleteModel(name='ParentsPage'),
        migrations.DeleteModel(name='TeachersPage'),
        migrations.DeleteModel(name='EducationPage'),
        migrations.DeleteModel(name='DocumentPage'),
        migrations.DeleteModel(name='StandardPage'),
        migrations.DeleteModel(name='PageDocument'),
        # Now delete the parent model
        migrations.DeleteModel(name='SectionIndexPage'),
    ]
