# Generated by Django 5.2.17 on 2026-08-22 17:36

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_homepage_announcement'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='cta_primary_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Посилання основної кнопки'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_primary_text',
            field=models.CharField(blank=True, default='Подати заяву на вступ', max_length=100, verbose_name='Текст основної кнопки'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_secondary_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Посилання другорядної кнопки'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_secondary_text',
            field=models.CharField(blank=True, default='Контакти та адреса', max_length=100, verbose_name='Текст другорядної кнопки'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_text',
            field=models.TextField(blank=True, default='Миколаївський ліцей №9 відкриває двері для допитливих, талановитих та вмотивованих учнів. Оберіть якісну освіту та впевнений старт у майбутнє!', help_text='Опис під заголовком заклику', verbose_name='Текст заклику (CTA)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_title',
            field=models.CharField(blank=True, default='Готові приєднатися до нашої ліцейної родини?', help_text='Головний заголовок блоку заклику до дії внизу сторінки', max_length=255, verbose_name='Заголовок заклику (CTA)'),
        ),
        migrations.CreateModel(
            name='AboutPageFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text='Наприклад: Сертифіковане укриття, Мультимедійні класи', max_length=150, verbose_name='Назва елемента простору')),
                ('description', models.TextField(help_text='Короткий опис облаштування та переваг для учнів', verbose_name='Опис оснащення та можливостей')),
                ('icon', models.CharField(default='bi-shield-check', help_text='Наприклад: bi-shield-check, bi-display, bi-trophy, bi-journal-bookmark', max_length=50, verbose_name='Іконка (Bootstrap Icons)')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='home.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutPageFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('question', models.CharField(help_text='Наприклад: Як вступити до Миколаївського ліцею №9?', max_length=300, verbose_name='Запитання')),
                ('answer', wagtail.fields.RichTextField(help_text='Розгорнута відповідь з можливістю додавати посилання та форматування', verbose_name='Відповідь')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='home.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutPageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('badge', models.CharField(default='Профіль', help_text='Наприклад: Точні науки, Мови та світ, Дослідження, Суспільство', max_length=100, verbose_name='Категорія / Бейдж')),
                ('title', models.CharField(help_text='Наприклад: Математика & IT, Філологічний напрям', max_length=150, verbose_name='Назва профілю / напряму')),
                ('description', models.TextField(help_text='Що вивчають учні на цьому напрямі та які навички здобувають', verbose_name='Опис напряму')),
                ('tags', models.CharField(blank=True, help_text='Наприклад: Математика, Інформатика, Алгоритми', max_length=255, verbose_name='Теги предметів (через кому)')),
                ('icon', models.CharField(default='bi-cpu-fill', help_text='Наприклад: bi-cpu-fill, bi-translate, bi-flask-fill, bi-bank', max_length=50, verbose_name='Іконка (Bootstrap Icons)')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_profiles', to='home.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutPageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('number', models.CharField(help_text='Наприклад: 1991, 500+, 100%, 45', max_length=50, verbose_name='Показник / Число')),
                ('title', models.CharField(help_text='Наприклад: Рік заснування, Учнів ліцею, Вчителів', max_length=100, verbose_name='Назва показника')),
                ('description', models.CharField(blank=True, help_text='Наприклад: Понад 30 років академічних традицій', max_length=200, verbose_name='Короткий підпис')),
                ('icon', models.CharField(default='bi-calendar-check', help_text='Наприклад: bi-calendar-check, bi-people-fill, bi-person-badge-fill, bi-trophy-fill', max_length=50, verbose_name='Іконка (Bootstrap Icons)')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='home.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutPageValuePillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text='Наприклад: Академічна якість та доброчесність', max_length=150, verbose_name='Назва цінності')),
                ('description', models.TextField(help_text='Коротке пояснення суті цієї цінності для учнів та педагогів', verbose_name='Опис цінності')),
                ('icon', models.CharField(default='bi-mortarboard-fill', help_text='Наприклад: bi-mortarboard-fill, bi-people-fill, bi-lightbulb-fill, bi-shield-fill-check', max_length=50, verbose_name='Іконка (Bootstrap Icons)')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_pillars', to='home.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
