# Generated by Django 5.2.17 on 2026-08-22 17:52

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_aboutpage_cta_primary_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='facilities_subtitle',
            field=models.CharField(blank=True, default='Створюємо комфортні, безпечні та високотехнологічні умови для кожного ліцеїста', max_length=255, verbose_name='Підзаголовок блоку інфраструктури'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='facilities_title',
            field=models.CharField(blank=True, default='Сучасний освітній простір', max_length=150, verbose_name='Заголовок блоку інфраструктури'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='faq_subtitle',
            field=models.CharField(blank=True, default='Основна інформація про організацію освітнього процесу та вступ до ліцею', max_length=255, verbose_name='Підзаголовок блоку FAQ'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='faq_title',
            field=models.CharField(blank=True, default='Часті запитання батьків та учнів', max_length=150, verbose_name='Заголовок блоку FAQ'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_badge',
            field=models.CharField(blank=True, default='Миколаївський ліцей №9', help_text='Текст бейджа над заголовком у шапці', max_length=100, verbose_name='Бейдж у шапці'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_title',
            field=models.CharField(blank=True, default='Наша місія', help_text='Заголовок картки місії', max_length=150, verbose_name='Заголовок блоку місії'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='profiles_subtitle',
            field=models.CharField(blank=True, default='Обирайте напрям, який відповідає талантам і прагненням майбутнього ліцеїста', max_length=255, verbose_name='Підзаголовок блоку профілів'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='profiles_title',
            field=models.CharField(blank=True, default='Освітні напрями та пріоритети', max_length=150, verbose_name='Заголовок блоку профілів'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='subpages_subtitle',
            field=models.CharField(blank=True, default='Ознайомтеся з історією, адміністрацією, педагогічним колективом та службами ліцею', max_length=255, verbose_name='Підзаголовок блоку підрозділів'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='subpages_title',
            field=models.CharField(blank=True, default='Розділи про наш ліцей', max_length=150, verbose_name='Заголовок блоку підрозділів'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='values_title',
            field=models.CharField(blank=True, default='Цінності ліцею', help_text='Заголовок картки цінностей', max_length=150, verbose_name='Заголовок блоку цінностей'),
        ),
        migrations.CreateModel(
            name='AboutPageHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text='Наприклад: Поглиблене вивчення предметів', max_length=150, verbose_name='Текст тези/переваги')),
                ('icon', models.CharField(default='bi-check-circle-fill', help_text='Наприклад: bi-check-circle-fill, bi-shield-lock-fill, bi-laptop, bi-stars', max_length=50, verbose_name='Іконка (Bootstrap Icons)')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='home.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
